[package]
name = "rwc"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]

[lib]
name = "rwc"
crate-type = ["dylib"]

