[package]
name = "plugin_r"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]

[lib]
name = "plugin_r"
crate-type = ["dylib"]

[dependencies]
library = { path = "../library" }


